apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kyverno/kyverno
    path: gitops-folder/kyverno/crds  # local folder with CRDs only
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

