apiVersion: v1
kind: Secret
metadata:
  name: app-crds
  annotations: 
  avp.kubernetes.io/path: "credentials/data/app"
type: Opaque
stringData:
  apikey: <api-key>
  username: <username>
  password: <password>
